import { Router } from 'express';
import authRoutes from './auth.routes.js';
import userRoutes from './user.routes.js';
import friendRoutes from './friend.routes.js';
import messageRoutes from './message.routes.js';
import callRoutes from './call.routes.js';
import notificationRoutes from './notification.routes.js';
import pushRoutes from './push.routes.js';
import groupRoutes from './group.routes.js';
import privacyRoutes from './privacy.routes.js';
import adminRoutes from './admin.routes.js';
import monitoringRoutes from './monitoring.routes.js';

export const apiRouter = Router();
apiRouter.use('/auth', authRoutes);
apiRouter.use('/users', userRoutes);
apiRouter.use('/friends', friendRoutes);
apiRouter.use('/messages', messageRoutes);
apiRouter.use('/calls', callRoutes);
apiRouter.use('/notifications', notificationRoutes);
apiRouter.use('/push', pushRoutes);
apiRouter.use('/groups', groupRoutes);
apiRouter.use('/privacy', privacyRoutes);
apiRouter.use('/admin', adminRoutes);
apiRouter.use('/monitoring', monitoringRoutes);
